### ISSUE TITLE
[Feature Request] - To be able to disable highlight links

### ISSUE THREAD

**Issue by farias-hecdin** [icholy/nvim-lsplinks#13]
Hello, how are you? 👋
I want to congratulate you on this wonderful plugin? 👍

If it's not too much to ask, I would like to be able to configure this plugin to disable the link highlighting feature in future updates.
The link highlighting is great, but it doesn't look good with my current color scheme. 🙏

Another solution could be that the highlight link becomes active when the cursor hovers over it.

**Comment by icholy** [comment]
I've added `setup` options which give more control over the highlights:

``` lua
lsplinks.setup({
    highlight = true,
    hl_group = "Underlined",
})
```

**Comment by farias-hecdin** [comment]
@icholy Thank you very much! 👍
