### ISSUE TITLE
Please do not keep images in the repo

### ISSUE THREAD

**Issue by chrisgrieser** [icholy/nvim-lsplinks#9]
nvim package managers install plugins by cloning them, having images in the repo increases the download size. More detailed explanation: https://www.reddit.com/r/neovim/comments/wsg5yx/attention_to_all_plugin_authors_newcomers_careful/

**Comment by icholy** [comment]
Sure, I'll just attach them here and reference the uploaded links.

![demo1](https://github.com/icholy/lsplinks.nvim/assets/943597/3f41f659-7b4a-407d-900b-2070ded22e6c)
![demo2](https://github.com/icholy/lsplinks.nvim/assets/943597/d96e39b5-508b-4efb-ac33-044de88dacce)
